# / home / asus / PycharmProjects / TrelloUzBot / env / bin / python / home / asus / PycharmProjects / TrelloUzBot / bot / bot.py
# Started...
# [{'id': '63ee9840e828354f23aaf303',
#   'badges': {'attachmentsByType': {'trello': {'board': 0, 'card': 0}}, 'location': False, 'votes': 0,
#              'viewingMemberVoted': False, 'subscribed': True, 'fogbugz': '', 'checkItems': 0, 'checkItemsChecked': 0,
#              'checkItemsEarliestDue': None, 'comments': 1, 'attachments': 0, 'description': True, 'due': None,
#              'dueComplete': False, 'start': None}, 'checkItemStates': None, 'closed': False, 'dueComplete': False,
#   'dateLastActivity': '2023-02-16T21:27:36.934Z', 'desc': 'edededed', 'descData': {'emoji': {}}, 'due': None,
#   'dueReminder': None, 'email': None, 'idBoard': '63ee35bdf19806bbf560df69', 'idChecklists': [],
#   'idList': '63ee35bdf19806bbf560df71', 'idMembers': ['63ea227728ee0b875a66f2f5'], 'idMembersVoted': [], 'idShort': 3,
#   'idAttachmentCover': None,
#   'labels': [{'id': '63ee35bd2f36f2348ad758f8', 'idBoard': '63ee35bdf19806bbf560df69', 'name': '', 'color': 'blue'}],
#   'idLabels': ['63ee35bd2f36f2348ad758f8'], 'manualCoverAttachment': False, 'name': 'bosingla', 'pos': 65535,
#   'shortLink': 'lN8pSbCo', 'shortUrl': 'https://trello.com/c/lN8pSbCo', 'start': None, 'subscribed': True,
#   'url': 'https://trello.com/c/lN8pSbCo/3-bosingla',
#   'cover': {'idAttachment': None, 'color': None, 'idUploadedBackground': None, 'size': 'normal', 'brightness': 'dark',
#             'idPlugin': None}, 'isTemplate': False, 'cardRole': None}, {'id': '63ee98403325d9e808f1f450', 'badges': {
#     'attachmentsByType': {'trello': {'board': 0, 'card': 0}}, 'location': False, 'votes': 0,
#     'viewingMemberVoted': False, 'subscribed': False, 'fogbugz': '', 'checkItems': 0, 'checkItemsChecked': 0,
#     'checkItemsEarliestDue': None, 'comments': 0, 'attachments': 0, 'description': True, 'due': None,
#     'dueComplete': False, 'start': None}, 'checkItemStates': None, 'closed': False, 'dueComplete': False,
#                                                                         'dateLastActivity': '2023-02-16T21:27:28.540Z',
#                                                                         'desc': 'olga', 'descData': {'emoji': {}},
#                                                                         'due': None, 'dueReminder': None, 'email': None,
#                                                                         'idBoard': '63ee35bdf19806bbf560df69',
#                                                                         'idChecklists': [],
#                                                                         'idList': '63ee35bdf19806bbf560df71',
#                                                                         'idMembers': [], 'idMembersVoted': [],
#                                                                         'idShort': 4, 'idAttachmentCover': None,
#                                                                         'labels': [{'id': '63ee35bd2f36f2348ad758f8',
#                                                                                     'idBoard': '63ee35bdf19806bbf560df69',
#                                                                                     'name': '', 'color': 'blue'}],
#                                                                         'idLabels': ['63ee35bd2f36f2348ad758f8'],
#                                                                         'manualCoverAttachment': False,
#                                                                         'name': 'tayyor', 'pos': 131071,
#                                                                         'shortLink': 'kmWZHNWX',
#                                                                         'shortUrl': 'https://trello.com/c/kmWZHNWX',
#                                                                         'start': None, 'subscribed': False,
#                                                                         'url': 'https://trello.com/c/kmWZHNWX/4-tayyor',
#                                                                         'cover': {'idAttachment': None, 'color': None,
#                                                                                   'idUploadedBackground': None,
#                                                                                   'size': 'normal',
#                                                                                   'brightness': 'dark',
#                                                                                   'idPlugin': None},
#                                                                         'isTemplate': False, 'cardRole': None},
#  {'id': '63ee98413ba5ab0bf4ac45cf',
#   'badges': {'attachmentsByType': {'trello': {'board': 0, 'card': 0}}, 'location': False, 'votes': 0,
#              'viewingMemberVoted': False, 'subscribed': False, 'fogbugz': '', 'checkItems': 0, 'checkItemsChecked': 0,
#              'checkItemsEarliestDue': None, 'comments': 0, 'attachments': 0, 'description': True, 'due': None,
#              'dueComplete': False, 'start': None}, 'checkItemStates': None, 'closed': False, 'dueComplete': False,
#   'dateLastActivity': '2023-02-16T21:27:49.086Z', 'desc': 'dededwdwed', 'descData': {'emoji': {}}, 'due': None,
#   'dueReminder': None, 'email': None, 'idBoard': '63ee35bdf19806bbf560df69', 'idChecklists': [],
#   'idList': '63ee35bdf19806bbf560df71', 'idMembers': [], 'idMembersVoted': [], 'idShort': 5, 'idAttachmentCover': None,
#   'labels': [{'id': '63ee35bd2f36f2348ad758e5', 'idBoard': '63ee35bdf19806bbf560df69', 'name': '', 'color': 'green'}],
#   'idLabels': ['63ee35bd2f36f2348ad758e5'], 'manualCoverAttachment': False, 'name': 'nimadur', 'pos': 196607,
#   'shortLink': 'nbpJq2p6', 'shortUrl': 'https://trello.com/c/nbpJq2p6', 'start': None, 'subscribed': False,
#   'url': 'https://trello.com/c/nbpJq2p6/5-nimadur',
#   'cover': {'idAttachment': None, 'color': None, 'idUploadedBackground': None, 'size': 'normal', 'brightness': 'dark',
#             'idPlugin': None}, 'isTemplate': False, 'cardRole': None}, {'id': '63ee984226ce0c98b93aa071', 'badges': {
#     'attachmentsByType': {'trello': {'board': 0, 'card': 0}}, 'location': False, 'votes': 0,
#     'viewingMemberVoted': False, 'subscribed': False, 'fogbugz': '', 'checkItems': 0, 'checkItemsChecked': 0,
#     'checkItemsEarliestDue': None, 'comments': 0, 'attachments': 0, 'description': False, 'due': None,
#     'dueComplete': False, 'start': None}, 'checkItemStates': None, 'closed': False, 'dueComplete': False,
#                                                                         'dateLastActivity': '2023-02-16T20:55:30.313Z',
#                                                                         'desc': '', 'descData': {'emoji': {}},
#                                                                         'due': None, 'dueReminder': None, 'email': None,
#                                                                         'idBoard': '63ee35bdf19806bbf560df69',
#                                                                         'idChecklists': [],
#                                                                         'idList': '63ee35bdf19806bbf560df71',
#                                                                         'idMembers': [], 'idMembersVoted': [],
#                                                                         'idShort': 6, 'idAttachmentCover': None,
#                                                                         'labels': [], 'idLabels': [],
#                                                                         'manualCoverAttachment': False,
#                                                                         'name': 'f,d;f,d;4', 'pos': 262143,
#                                                                         'shortLink': 'A1cEl6fr',
#                                                                         'shortUrl': 'https://trello.com/c/A1cEl6fr',
#                                                                         'start': None, 'subscribed': False,
#                                                                         'url': 'https://trello.com/c/A1cEl6fr/6-fdfd4',
#                                                                         'cover': {'idAttachment': None, 'color': None,
#                                                                                   'idUploadedBackground': None,
#                                                                                   'size': 'normal',
#                                                                                   'brightness': 'dark',
#                                                                                   'idPlugin': None},
#                                                                         'isTemplate': False, 'cardRole': None},
#  {'id': '63ee9842342d8d0ebc18bc63',
#   'badges': {'attachmentsByType': {'trello': {'board': 0, 'card': 0}}, 'location': False, 'votes': 0,
#              'viewingMemberVoted': False, 'subscribed': False, 'fogbugz': '', 'checkItems': 0, 'checkItemsChecked': 0,
#              'checkItemsEarliestDue': None, 'comments': 0, 'attachments': 0, 'description': False, 'due': None,
#              'dueComplete': False, 'start': None}, 'checkItemStates': None, 'closed': False, 'dueComplete': False,
#   'dateLastActivity': '2023-02-16T20:55:30.831Z', 'desc': '', 'descData': {'emoji': {}}, 'due': None,
#   'dueReminder': None, 'email': None, 'idBoard': '63ee35bdf19806bbf560df69', 'idChecklists': [],
#   'idList': '63ee35bdf19806bbf560df71', 'idMembers': [], 'idMembersVoted': [], 'idShort': 7, 'idAttachmentCover': None,
#   'labels': [], 'idLabels': [], 'manualCoverAttachment': False, 'name': 'af,d;f,a', 'pos': 327679,
#   'shortLink': 'wOujMnsK', 'shortUrl': 'https://trello.com/c/wOujMnsK', 'start': None, 'subscribed': False,
#   'url': 'https://trello.com/c/wOujMnsK/7-afdfa',
#   'cover': {'idAttachment': None, 'color': None, 'idUploadedBackground': None, 'size': 'normal', 'brightness': 'dark',
#             'idPlugin': None}, 'isTemplate': False, 'cardRole': None}]
# #